---
- name: Post Install - Configure Proxmox VE
  hosts: proxmox
  become: true
  tasks:

    - name: Disable Proxmox enterprise repository
      lineinfile:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        regexp: '^deb .*'
        line: '# deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
        state: present

    - name: Remove Ceph enterprise repository
      file:
        path: /etc/apt/sources.list.d/ceph.list
        state: absent

    - name: Add Proxmox non-subscription repository
      copy:
        dest: /etc/apt/sources.list.d/pve-no-subscription.list
        content: |
          deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription

    - name: Add Proxmox keyring
      apt_key:
        url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
        state: present

    - name: Update package lists
      apt:
        update_cache: yes

    - name: Upgrade the system
      apt:
        upgrade: dist

    - name: Install common tools
      apt:
        name: # Add/Remove whatever you want.
          - wget
          - curl
          - git
        state: present

    - name: Set hostname
      hostname:
        name: overlord

    - name: Remove subscription nag banner
      shell: |
        echo "DPkg::Post-Invoke { \"rm -f /var/lib/apt/lists/partial/*pve-enterprise*\"; };" > /etc/apt/apt.conf.d/99pvebanner
      args:
        creates: /etc/apt/apt.conf.d/99pvebanner
